site_name: ∂'Alembert
theme:
  logo: https://lam-ijlra.github.io/ijlra_cheat_sheets/img/logo.jpg
  favicon: https://lam-ijlra.github.io/ijlra_cheat_sheets/img/logo.jpg
  name: material
  features:
    - navigation.indexes
    - navigation.footer
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - markdownextradata

extra:
  representatives:
    [
      { name: "Sami Azzaz", email: "sami.azzaz@dalembert.upmc.fr", room: 512 },
      {
        name: "Lucie Jean-Labadye",
        email: "lucie.jean-labadye@dalembert.upmc.fr",
        room: 311,
      },
      {
        name: "Emanuele Tamburini",
        email: "emanuele.tamburini@sorbonne-universite.fr",
        room: 418,
      },
      {
        name: "Elettra Figa-Talamanca",
        email: "elettra.figa-talamanca@dalembert.upmc.fr",
        room: 306,
      },
      { name: "Zichen Li", email: "zichen.li@dalembert.upmc.fr", room: 418 },
    ]
  it_team: {}
  administrators:
    [
      {
        name: "Nathan Kasongo",
        email: "nathan.kasongo@dalembert.upmc.fr",
        room: "44-54 516",
        team: "MPIA",
      },
      {
        name: "Catherine Dejancourt",
        email: "dejancourt@dalembert.upmc.fr",
        room: "44-54 520",
        team: "MISES",
      },
      {
        name: "Olivier Labbey",
        email: "labbey@dalembert.upmc.fr",
        room: "44-54 524",
        team: "FCIH / CEPT",
      },
      {
        name: "Matanael Davillé",
        email: "matanael.daville@dalembert.upmc.fr",
        room: "44-54 516",
        team: "LAM",
      },
    ]

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

nav:
  - Guide:
      - guide/index.md
      - "Before You Arrive": guide/before.md
      - "Upon Arrival": guide/upon.md
      - "Accounts": guide/accounts.md
      - "Email Setup": guide/email.md
      - "Internet Access": guide/internet.md
      - "Contacts": guide/contacts.md
      - "Administrators": guide/administrators.md
      - "Room Booking": guide/room.md
      - "SSH": guide/ssh.md
      - "Printers": guide/printers.md
      - "Web Services": guide/webservices.md
      - "Transportation": guide/transports.md
      - "CROUS (Dining)": guide/crous.md
      - "Doctoral missions": guide/missions.md
  - contributing.md
